# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSlotPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_manager.GymSlot')),
            ],
        ),
        migrations.RenameModel(
            old_name='TeamPlayers',
            new_name='TeamPlayer',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nick_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gymslotplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team_manager.Player'),
        ),
    ]
