# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0004_auto_20170404_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymslot',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True),
        ),
    ]
