# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0006_auto_20170404_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
