# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0007_auto_20170404_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='outside_shooting',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='defend_fast',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='defend_large',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='movement',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='passing',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='rebounding',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='scoring',
            field=models.IntegerField(default=2),
        ),
    ]
