# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0008_auto_20170405_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ball_handler',
            field=models.BooleanField(default=False),
        ),
    ]
