# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0009_player_ball_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='size',
            field=models.IntegerField(blank=True, choices=[('1', 'Small'), ('2', 'Medium'), ('4', 'Large')], null=True),
        ),
    ]
