# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0013_auto_20170419_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
