# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0015_auto_20170419_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='team_manager.Team'),
        ),
    ]
