# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0016_auto_20170420_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymsession',
            name='gym_slot',
        ),
        migrations.AddField(
            model_name='gymslot',
            name='gym_sessions',
            field=models.ManyToManyField(to='team_manager.GymSession'),
        ),
    ]
