# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0018_auto_20170420_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymsession',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('first_name',)},
        ),
    ]
