# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0020_manual_20170421_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('played', models.IntegerField(default=2)),
                ('won', models.IntegerField(default=2)),
                ('win_loss', models.FloatField(default=2)),
                ('game_date', models.DateField()),
            ],
            options={
                'db_table': 'vw_player_win_summary',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='team',
            name='point_differential',
            field=models.IntegerField(null=True),
        ),
    ]
