# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0022_manual_20170424_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlayerSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=2)),
                ('won', models.IntegerField(default=2)),
                ('win_loss', models.FloatField(default=2)),
                ('point_differential', models.FloatField(default=2)),
                ('relationship', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'player_player_stats',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='team_manager.Player'),
        ),
    ]
