# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 21:02
from __future__ import unicode_literals

from django.db import migrations
import sqlparse

class Migration(migrations.Migration):


    run_sql = """ CREATE TABLE `player_player_stats` (
                  `id` varchar(36) DEFAULT NULL,
                  `player_id` int(11) NOT NULL,
                  `other_player_id` int(11) NOT NULL,
                  `played` decimal(23,0) DEFAULT NULL,
                  `won` decimal(25,0) DEFAULT NULL,
                  `win_loss` decimal(29,4) DEFAULT NULL,
                  `point_differential` decimal(14,4) DEFAULT NULL,
                  `relationship` varchar(4) NOT NULL DEFAULT ''
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8"""
    rollback_sql = "DROP TABLE IF EXISTS player_player_stats;"

    dependencies = [
        ('team_manager', '0023_auto_20170425_1410'),
    ]

    operations = [
        migrations.RunSQL(
            sqlparse.format(run_sql), 
            sqlparse.format(rollback_sql)
        ),
    ]
