# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0026_player_last_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
