# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0027_player_last_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymslot',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
