# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0028_gymslot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ninety_day_games_played',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='ninety_day_plus_minus',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='ninety_day_win_percentage',
            field=models.FloatField(default=2),
        ),
    ]
