# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0029_auto_20170505_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score_contribution',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='win_contribution',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=2),
        ),
    ]
