# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sqlparse
from team_manager.models import Player
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):


    def update_players(apps, schema_editor):

        players = Player.objects.all()
        for player in players:
            try:
                print "UPDATING %s" % (player)
                user = User.objects.filter(first_name = player.first_name).filter(last_name = player.last_name)
                if len(user) > 0:
                    player.user = user[0]
                    player.save()
                else:
                    user_name = "%s_%s" % (player.first_name, player.last_name)
                    password = make_password('123')
                    user = User.objects.create(username=user_name, first_name=player.first_name, last_name=player.last_name, password=password)
                    player.user = user
                    player.save()

            except:
                print "FAILED ON %s" % (player)

    def roll_back(apps, schema_editor):
        print "Nothing"

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_manager', '0030_auto_20170522_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(update_players, roll_back)
    ]

